const gulp = require('gulp');
const del = require('del');

var clean = gulp.task('clean', function () {
  return del([
    './dist',
    // clean up the parts generated by ngc
    './src/**/*.ngfactory.ts',
    './src/**/*.ngstyle.ts',
    './src/**/*.ngsummary.json'
  ]);
});

var tidyup = gulp.task('tidyup', function () {
  return del(['./dist/app/**', './dist/buildingblocks/**', './dist/shared/**'])
});

module.exports.clean = clean;
